### PR TITLE
Feature/animals table

### PR DESCRIPTION
**Pull request by Ali-0111**
### Animals Table
- Database created and `Animals` table added, codes are available in `schema.sql`
- `records` inserted based on project requirements and codes are available in `data.sql`
- `queries` added and codes are available in `quries.sql`

-  All items added to the table.
image

- All animals whose name ends 'mon'
image

- The name of all animals born between 2016 and 2019. 
image

- The name of all animals that are neutered and have less than 3 escape attempts.
image

- Name of all animals named either "Agumon" or "Pikachu".
image

- name and escape attempts of animals that weigh more than 10.5kg 
image

- Find all animals that are neutered.
image

- Find all animals not named Gabumon.
image

- Find all animals with a weight between 10.4kg and 17.3kg (including the animals with the weights that equals precisely 10.4kg or 17.3kg)
image

### CODE REVIEW

**Comment by Ali-0111** [comment]
- [ ] All items added to the table.
image

**Review by Gambit142 — COMMENTED** [review]
Hi @Ali-0111 👋,, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- You used the wrong Gitflow. Your pull request ought to be from a feature branch to the `dev` branch as the `base` branch. Kindly use the correct Gitflow 👍 
- Your README is not professional. Kindly provide relevant information for each section. 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Ali-0111** [comment]
@Gambit142 
Thanks, I will do the changes required

**Review by nedjwab — APPROVED** [review]
# 🟢 Project Approved! 🏆

## Hi  @Ali-0111   👋

Your project is complete! ✔️✔  🏁

Your code was very professional 💯

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉

 
## Highlights 🌟

- ✔️ Descriptive commmit messsages
- ✔️ Descriptive PR description
- ✔️ No linter Errors
-  ✔️ Queries are correct 

- The code is top-notch! 💯 and have a huge potential.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
